### ISSUE TITLE
File Analysis fails

### ISSUE THREAD

**Issue by Poeschl** [eyal0/OctoPrint-PrintTimeGenius#145]
#### OctoPrint Version:
`1.3.11`

#### PrintTimeGenius Version (if you know):
`1.3.4`

#### Cura Version:
`4.1.0`

#### What did you try:

* Goto Settings
* Select PrintTimeGenius Plugin settings
* Select gcode file ([Uploaded file.zip](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/3409707/Uploaded.file.zip))
* Click `Analyse`

#### What happenned:

* File got not analysed
* PrintTimeGenius throws an error (see below)

#### What did you expect to happen:

* Get the file analysed and get a expected printing time

#### Log

```
2019-07-19 08:18:31,186 Not running built-in analysis.
2019-07-19 08:18:31,187 Disabled: "/opt/OctoPrint/venv/bin/python2" "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_gcode_comments.py" "/home/printifix/.octoprint/uploads/marpoe/Stecker_multi.gcode"
2019-07-19 08:18:31,187 Running: "/opt/OctoPrint/venv/bin/python2" "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py" marlin-calc "/home/printifix/.octoprint/uploads/marpoe/Stecker_multi.gcode" "M221 S100
M220 S100
M200 D0
M200 D1.75
M92 X80.00 Y80.00 Z400.00 E435.00
M203 X2500.00 Y2500.00 Z100.00 E25.00
M201 X500.00 Y500.00 Z100.00 E5000.00
M204 P500.00 R1000.00 T5000.00
M205 B20000.00 E5.00 S0.00 T0.00 X20.00 Y20.00 Z0.40 J0.02"
2019-07-19 08:18:31,702 Failed to run '"/opt/OctoPrint/venv/bin/python2" "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py" marlin-calc "/home/printifix/.octoprint/uploads/marpoe/Stecker_multi.gcode" "M221 S100
M220 S100
M200 D0
M200 D1.75
M92 X80.00 Y80.00 Z400.00 E435.00
M203 X2500.00 Y2500.00 Z100.00 E25.00
M201 X500.00 Y500.00 Z100.00 E5000.00
M204 P500.00 R1000.00 T5000.00
M205 B20000.00 E5.00 S0.00 T0.00 X20.00 Y20.00 Z0.40 J0.02"'
Traceback (most recent call last):
  File "/opt/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_PrintTimeGenius/__init__.py", line 318, in _do_analysis
    raise Exception(results_err)
Exception: Running: "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/marlin-calc.x86_64" "/home/printifix/.octoprint/uploads/marpoe/Stecker_multi.gcode" "M221 S100
M220 S100
M200 D0
M200 D1.75
M92 X80.00 Y80.00 Z400.00 E435.00
M203 X2500.00 Y2500.00 Z100.00 E25.00
M201 X500.00 Y500.00 Z100.00 E5000.00
M204 P500.00 R1000.00 T5000.00
M205 B20000.00 E5.00 S0.00 T0.00 X20.00 Y20.00 Z0.40 J0.02"
Junction deviation enabled
Processed 21699 Gcodes and 53 Mcodes. 20905 blocks
Total time: inf
Traceback (most recent call last):
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py", line 90, in <module>
    main()
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py", line 63, in main
    result.update(json.loads(line))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

2019-07-19 08:18:31,703 Running: "/opt/OctoPrint/venv/bin/python2" "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_gcode_comments.py" "/home/printifix/.octoprint/uploads/marpoe/Stecker_multi.gcode" --parsers slic3r_pe_print_time slic3r_pe_print_time_remaining
2019-07-19 08:18:32,220 Sarge output: 
2019-07-19 08:18:32,220 Result: {}

2019-07-19 08:18:32,220 Merged result: {'analysisPending': True}
```

Issue as requested on #128

**Comment by vogtitec** [comment]
I have the same problem since a while, today updated to PrintTImeGenius 1.3.4, but the error remains, print time is not calculated. I'm using Octoprint 1.3.11. Here is the last log:
````
2019-07-21 18:33:17,649 Not running built-in analysis.
2019-07-21 18:33:17,654 Disabled: "/home/pi/oprint/bin/python2" "/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_gcode_comments.py" "/home/pi/.octoprint/uploads/E12_PLA_Intex_Planeholder_mod.gcode"
2019-07-21 18:33:17,655 Running: "/home/pi/oprint/bin/python2" "/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py" marlin-calc "/home/pi/.octoprint/uploads/E12_PLA_Intex_Planeholder_mod.gcode" "M200 D1.75
M200 D0
M92 X80.00 Y80.00 Z400.00 E216.00
M203 X300.00 Y300.00 Z5.00 E0.00
M201 X800 Y800 Z100 E10000
M204 P800.00 R3000.00 T800.00
M205 B20000 E0.00 S0.00 T0.00 X8.00 Y8.00 Z0.30"
2019-07-21 18:33:24,463 Failed to run '"/home/pi/oprint/bin/python2" "/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py" marlin-calc "/home/pi/.octoprint/uploads/E12_PLA_Intex_Planeholder_mod.gcode" "M200 D1.75
M200 D0
M92 X80.00 Y80.00 Z400.00 E216.00
M203 X300.00 Y300.00 Z5.00 E0.00
M201 X800 Y800 Z100 E10000
M204 P800.00 R3000.00 T800.00
M205 B20000 E0.00 S0.00 T0.00 X8.00 Y8.00 Z0.30"'
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_PrintTimeGenius/__init__.py", line 318, in _do_analysis
    raise Exception(results_err)
Exception: Running: "/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/marlin-calc.armv7l" "/home/pi/.octoprint/uploads/E12_PLA_Intex_Planeholder_mod.gcode" "M200 D1.75
M200 D0
M92 X80.00 Y80.00 Z400.00 E216.00
M203 X300.00 Y300.00 Z5.00 E0.00
M201 X800 Y800 Z100 E10000
M204 P800.00 R3000.00 T800.00
M205 B20000 E0.00 S0.00 T0.00 X8.00 Y8.00 Z0.30"
..Processed 232707 Gcodes and 18 Mcodes. 222262 blocks
Total time: inf
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py", line 90, in <module>
    main()
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py", line 63, in main
    result.update(json.loads(line))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
````
The gcode was created with Simplify3D. Any suggestions, since about a month ago, everything worked fine... ?
Thank you!
