### ISSUE TITLE
PTG seens freeze while calculating the time, but on logs it says Failed to run

### ISSUE THREAD

**Issue by fellipec** [eyal0/OctoPrint-PrintTimeGenius#285]
**Describe the bug**
Either while clicking "Analyze" button or after sending a file through Cura or Prusa Slicer, the analysis of the file never ends. Cura just hangs on "Waiting for Octoprint analyze the file", Prusa Slicer don't report anything and the print never start unless I open the Octoprint and manually click "Print" and while using the Octorprint interface to ask for a file analysis, the hourglass icon stays forever.

The user have no indication whatsoever that the analysis failed. On logs you got this error:

```
2022-07-08 17:57:07,041 Failed to run '"/home/pi/OctoPrint/venv/bin/python3" "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py" marlin-calc "/home/pi/.octoprint/uploads/Caixa-de-Brocas-v3-LidN-LidN.gcode" "M92 X80.08 Y79.44 Z E135.16"'
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/octoprint_PrintTimeGenius/__init__.py", line 339, in _do_analysis
    raise Exception(results_err)
Exception: Running: "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/octoprint_PrintTimeGenius/analyzers/marlin-calc.aarch64" "/home/pi/.octoprint/uploads/Caixa-de-Brocas-v3-LidN-LidN.gcode" "M92 X80.08 Y79.44 Z E135.16"
Read up all remaining commands
Processed 68891 Gcodes and 122 Mcodes. 68217 blocks
Total time: inf
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py", line 97, in <module>
    main()
  File "/home/pi/OctoPrint/venv/lib/python3.9/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py", line 65, in main
    result.update(json.loads(line))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 25 (char 24)

```

**To Reproduce**
Use Cura or Prusa Slicer to send a gcode file to Octoprint, or click on the wrench icon on Octoprint, click on Print Time Genius Plugin, click on a file in the box "Files to analyze" and click in "Analyze"

**Expected behavior**
The expected print time should be show as usual OR some error be reported into the user interface and allow the print starts as normal.

**OctoPrint Version:**
1.8.1

**PrintTimeGenius Version (if you know):**
2.2.8

[plugin_PrintTimeGenius_engine (4).log](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/9075069/plugin_PrintTimeGenius_engine.4.log)
[Caixa-de-Brocas-v3-LidN-LidN.gcode.txt](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/9075070/Caixa-de-Brocas-v3-LidN-LidN.gcode.txt)

**Comment by eyal0** [comment]
Your problem is described here: https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems#it-isnt-working-and-in-the-log-i-see-total-time-inf

If the instructions there don't solve your problem, re-open this issue please.
