### ISSUE TITLE
Support for files on the machine's SD card

### ISSUE THREAD

**Issue by kazibole** [eyal0/OctoPrint-PrintTimeGenius#42]
**Does this plugin support files on the SD card?**

--------------

Before reporting, check if your problem is here:
https://github.com/eyal0/OctoPrint-PrintTimeGenius/wiki/Common-problems

Please fill this out:

OctoPrint Version: 1.3.9-rc3

PrintTimeGenius Version (if you know): 1.0.7

What did you try: Start print from machine's SD card, initiated from the machine's LCD.

What happenned: The following error repeats in the log:

```
2018-07-18 22:29:52,804 Failed to estimate, ignoring.
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_PrintTimeGenius/__init__.py", line 110, in estimate
    statisticalTotalPrintTime, statisticalTotalPrintTimeType)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_PrintTimeGenius/__init__.py", line 67, in _genius_estimate
    metadata = self._file_manager.get_metadata(self._origin, self._path)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/filemanager/__init__.py", line 599, in get_metadata
    return self._storage(destination).get_metadata(path)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/filemanager/__init__.py", line 690, in _storage
    raise NoSuchStorage("No storage configured for destination {destination}".format(**locals()))
NoSuchStorage: No storage configured for destination sdcard
```

What did you expect to happen: The print time to be estimated. Does this plugin support files on the SD card?

If relevant, upload the PrintTimeGenius log and any problematic gcode files (you might need to rename them).

[plugin_PrintTimeGenius_engine.log](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/2207750/plugin_PrintTimeGenius_engine.log)

**Comment by eyal0** [comment]
Thanks for your report.

This is just a cosmetic issue that resolves itself when the analysis is complete.  It'll be fixed in the next version.
