### ISSUE TITLE
No closing quotation error

### ISSUE THREAD

**Issue by michalzielanski** [eyal0/OctoPrint-PrintTimeGenius#59]
OctoPrint Version: 1.3.9
PrintTimeGenius Version (if you know): 1.1.0

Error log:
```
2018-07-26 20:44:23,827 Not running built-in analysis.
2018-07-26 20:44:23,833 Disabled: "/home/pi/oprint/bin/python" "/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_gcode_comments.py" "/home/pi/.octoprint/uploads/lacznik_test.gcode"
2018-07-26 20:44:23,834 Running: "/home/pi/oprint/bin/python" "/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py" "marlin-calc" "/home/pi/.octoprint/uploads/lacznik_test.gcode" "M220 S100"
M204 S1000"
2018-07-26 20:44:23,838 Failed to run '"/home/pi/oprint/bin/python" "/home/pi/oprint/lib/python2.7/site-packages/octoprint_PrintTimeGenius/analyzers/analyze_progress.py" "marlin-calc" "/home/pi/.octoprint/uploads/lacznik_test.gcode" "M220 S100"
M204 S1000"'
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_PrintTimeGenius/__init__.py", line 231, in _do_analysis
    popen = subprocess.Popen(shlex.split(command), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
```

Gcode:
[lacznik test.gcode.zip](https://github.com/eyal0/OctoPrint-PrintTimeGenius/files/2233458/lacznik.test.gcode.zip)

**Comment by eyal0** [comment]
How strange, there is an extra quotation in your config! Is it also in .octoprint/config.yml ? I wonder how it got there? Maybe you executed a M220 S100 command with quotations?
