### ISSUE TITLE
Failed to estimate ?

### ISSUE THREAD

**Issue by alexisml** [eyal0/OctoPrint-PrintTimeGenius#86]
OctoPrint Version: 1.3.9
PrintTimeGenius Version: 1.2

What did you try:
Printing :)

What happenned:
Got the star but no estimate (but I DO ghet a total time estimate)

![image](https://user-images.githubusercontent.com/16224395/46443827-9322c380-c745-11e8-84b9-72fdccc371f2.png)

What did you expect to happen:
Get the time remaining

I've chequed the logs and there are a ton of lines that go:
`2018-10-03 22:19:58,979 Failed to estimate
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_PrintTimeGenius/__init__.py", line 122, in estimate
    default_result = super(GeniusEstimator, self).estimate(
TypeError: super(type, obj): obj must be an instance or subtype of type
2018-10-03 22:19:59,488 Failed to estimate
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_PrintTimeGenius/__init__.py", line 122, in estimate
    default_result = super(GeniusEstimator, self).estimate(
TypeError: super(type, obj): obj must be an instance or subtype of type`

**Comment by alexisml** [comment]
Well, I disabled and reenabled to plugin and it got to work properly. Closing!
